name: GitHub Actions Demo

on:
  # Запускать workflow при каждом push в main ветку
  push:
    branches:
      - main

jobs:
  run-server:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Шаг 3: Устанавливаем зависимости (если есть)
      #- name: Install dependencies
       # run: |
        #  python -m pip install --upgrade pip
         # pip install -r requirements.txt  # Если у вас есть requirements.txt

      # Шаг 4: Запускаем сервер
      - name: Run server
        run: |
          # Запускаем сервер в фоновом режиме
          nohup python simple_web_server.py > server.log 2>&1 &
          echo "Server started..."

      # Шаг 5: Ждем некоторое время, чтобы сервер успел запуститься
      - name: Wait for server to start
        run: sleep 10

      # Шаг 6: Проверяем логи сервера
      - name: Check server logs
        run: cat server.log

      # Шаг 7: Остановка сервера (опционально)
      - name: Stop server
        if: always()  # Всегда выполняется, даже если предыдущие шаги завершились с ошибкой
        run: |
          pkill -f simple_web_server.py
          echo "Server stopped."